#!/usr/bin/env node
/* vim: set syntax=javascript ft=javascript : */
const parseHeaders = require('parse-headers');
const unflatten = require('flat').unflatten;
const escape = require('escape-html');

let data = "";
process.stdin.on('data', packet => {
  data += packet.toString();
});

process.stdin.on('end', () => {
  // Parse the playlist format, and remove any empty newlines
  let [playlistInfo, ...tracks] = data.split('%%\n').filter(i => i.trim().length);

  // Parse the playlist info
  let playlist = unflatten(parseHeaders(playlistInfo));

  // Extract the pertenant fields from the track
  let children = tracks.map(trackString => {
    // Parse the track key/value line by line
    let track = unflatten(parseHeaders(trackString));

    return `<track>
      <location>${escape(track.source)}</location>
      <creator>${escape(track.artist)}</creator>
      <title>${escape(track.name)}</title>
      <trackNum>${escape(track.index)}</trackNum>
    </track>`;
  }).join('\n');

  console.log('<playlist version="1" xmlns="http://xspf.org/ns/0/">');
  console.log(  `<title>${escape(playlist.name)}</title>`);
  console.log(  `<annotation>${Buffer.from(playlist.description, 'base64')}</annotation>`);
  console.log(  `${playlist.link}`);
  console.log(  `<trackList>`);
  console.log(    children);
  console.log(  `</trackList>`);
  console.log('</playlist>');
});
