#!/usr/bin/env node
/* vim: set syntax=javascript ft=javascript : */
const parseHeaders = require('parse-headers');
const unflatten = require('flat').unflatten;
const escape = require('escape-html');

let data = "";
process.stdin.on('data', packet => {
  data += packet.toString();
});

process.stdin.on('end', () => {
  // Parse the playlist format, and remove any empty newlines
  let tracks = data.split('%%\n').filter(i => i.trim().length);

  // Extract the pertenant fields from the track
  let children = tracks.map(trackString => {
    // Parse the track key/value line by line
    let track = unflatten(parseHeaders(trackString));

    return `<item>
      <title>${escape(track.name)}</title>
      <link>${escape(track.source)}</link>
      <dc:creator>${escape(track.artist)}</dc:creator>
    </item>`;
  }).join('\n');

  console.log('<rss version="2.0">');
  console.log(  `<title>8Tracks playlist</title>`);
  console.log(  `<link>https://8tracks.com</link>`);
  console.log(  children);
  console.log('</rss>');
});
