#!/usr/bin/env node
/* vim: set syntax=javascript ft=javascript : */
const Promise = require('bluebird'),
      request = require('request-promise'),
      eightTracksFetchMix = require('./8tracks-fetch-mix');

// Given a mix id, get the title for the mix.
function getTitleForMix(data) {
  let url = data;
  if (!isNaN(parseInt(data))) {
    url = `https://8tracks.com/mixes/${data}`;
  }

  // Prefix urls with http if they aren't already prefixed
  if (!url.startsWith('http')) {
    url = `http://${url}`;
  }

  return eightTracksFetchMix.convertMixUrlToMixId(url).then(body => {
    for (let key in body) {
      console.log(`${key}: ${body[key]}`);
    }
  });
}


getTitleForMix(process.argv[2]).catch(console.error);
